# Generated by Django 2.2.14 on 2020-10-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='users',
            name='level',
        ),
    ]
