# Generated by Django 2.2.14 on 2020-10-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False, null=True, verbose_name='Aktywny'),
        ),
    ]
