# Generated by Django 2.2.14 on 2020-07-18 14:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=ckeditor.fields.RichTextField(verbose_name='Pełna treść'),
        ),
    ]
