# Generated by Django 2.2.14 on 2020-07-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20200718_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(verbose_name='Pełna treść'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short',
            field=models.TextField(max_length=300, verbose_name='Skrót'),
        ),
    ]
