# Generated by Django 2.2.14 on 2020-07-23 20:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0004_auto_20200719_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Pełna treść'),
        ),
    ]
