# Generated by Django 2.2.14 on 2020-10-06 17:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0005_auto_20200723_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000000, null=True, verbose_name='Pełna treść'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short',
            field=models.TextField(max_length=1000, verbose_name='Skrót'),
        ),
    ]
